"""Traductions des textes à l'écran. Clé : le texte français tel qu'il figure dans generer.py.

Registre : vouvoiement en allemand (Sie), espagnol (usted), italien (Lei) et néerlandais (u) ;
tutoiement en polonais, l'usage courant des applications grand public.
Les nombres suivent l'usage de chaque langue (séparateur de milliers, abréviation du million).
"""

LANGUES = {"en": "English", "de": "Deutsch", "es": "Español", "it": "Italiano", "nl": "Nederlands", "pl": "Polski"}

CLES = [
    "Connaissez-vous",
    "Saviez-vous que Michelin Truckfly existe aussi",
    "pour les propriétaires d'établissements&nbsp;?",
    "Restaurant", "Parking", "Station-service", "Station de lavage", "Garage",
    "La communauté en chiffres",
    "2,3 M", "702 000", "135 000",
    "téléchargements", "pays européens", "langues disponibles", "utilisateurs", "établissements référencés",
    "Vous avez un établissement sur Michelin Truckfly&nbsp;?",
    "Mettez à jour vos informations&nbsp;!",
    "Pas encore présent sur Michelin Truckfly&nbsp;?",
    "Créez votre compte et ajoutez votre établissement&nbsp;!",
    "Nom et coordonnées", "Services proposés", "Photos", "Horaires",
    "Retrouvez les commentaires et les photos de la communauté",
    "Mon lieu", "Mon compte",
    "Mon établissement", "Mes services et photos", "Mes horaires d'ouverture", "Mes commentaires",
    "Nom de l'établissement", "Adresse", "Code postal", "Ville", "Téléphone",
    "Enregistrer", "✓ Enregistré",
    "Mes services", "Restaurant routier", "Douches", "Parking poids lourds", "Wifi", "Toilettes", "Parking surveillé",
    "Ma photo", "Glissez votre photo ici",
    "Lundi", "Mardi", "Mercredi", "Début", "Fin", "Journée continue", "Dupliquer",
    "3 mai", "24 avril", "18 avril",
    "AVIS_DENIS", "AVIS_PASCAL", "AVIS_EMILIE",
    "Ma réponse", "REPONSE", "Répondre", "Signaler",
    "Photos de la communauté", "Ajoutée par {qui}",
    "Pour promouvoir mon établissement,", "connectez-vous sur le site internet.",
]

T = {
    "en": [
        "Do you know",
        "Did you know that Michelin Truckfly is also",
        "for business owners?",
        "Restaurant", "Parking", "Fuel station", "Truck wash", "Garage",
        "The community in numbers",
        "2.3M", "702,000", "135,000",
        "downloads", "European countries", "languages available", "users", "listed businesses",
        "Already have a business on Michelin Truckfly?",
        "Update your information!",
        "Not on Michelin Truckfly yet?",
        "Create your account and add your business!",
        "Name and contact details", "Services offered", "Photos", "Opening hours",
        "Find the community's reviews and photos",
        "My place", "My account",
        "My business", "My services and photos", "My opening hours", "My reviews",
        "Business name", "Address", "Postcode", "City", "Phone",
        "Save", "✓ Saved",
        "My services", "Truck stop restaurant", "Showers", "HGV parking", "Wi-Fi", "Toilets", "Secure parking",
        "My photo", "Drag your photo here",
        "Monday", "Tuesday", "Wednesday", "Start", "End", "Open all day", "Duplicate",
        "3 May", "24 April", "18 April",
        "Great welcome, hearty meals, clean showers, breakfast in the morning, nothing to fault. I recommend it! Thanks to the whole team!",
        "Restaurant open, varied and affordable menu. Thanks!",
        "Warm welcome and very hearty meals, it was perfect!",
        "My reply", "Thank you so much for your review, Denis! See you soon!", "Reply", "Report",
        "Community photos", "Added by {qui}",
        "To promote your business,", "log in on the website.",
    ],
    "de": [
        "Kennen Sie",
        "Wussten Sie, dass es Michelin Truckfly auch",
        "für Betriebsinhaber gibt?",
        "Restaurant", "Parkplatz", "Tankstelle", "Waschanlage", "Werkstatt",
        "Die Community in Zahlen",
        "2,3 Mio.", "702.000", "135.000",
        "Downloads", "europäische Länder", "verfügbare Sprachen", "Nutzer", "gelistete Betriebe",
        "Ihr Betrieb ist schon auf Michelin Truckfly?",
        "Aktualisieren Sie Ihre Daten!",
        "Noch nicht auf Michelin Truckfly?",
        "Erstellen Sie Ihr Konto und fügen Sie Ihren Betrieb hinzu!",
        "Name und Kontaktdaten", "Angebotene Leistungen", "Fotos", "Öffnungszeiten",
        "Bewertungen und Fotos der Community ansehen",
        "Mein Standort", "Mein Konto",
        "Mein Betrieb", "Meine Leistungen und Fotos", "Meine Öffnungszeiten", "Meine Bewertungen",
        "Name des Betriebs", "Adresse", "Postleitzahl", "Ort", "Telefon",
        "Speichern", "✓ Gespeichert",
        "Meine Leistungen", "Autohof-Restaurant", "Duschen", "Lkw-Parkplatz", "WLAN", "Toiletten", "Bewachter Parkplatz",
        "Mein Foto", "Foto hierher ziehen",
        "Montag", "Dienstag", "Mittwoch", "Beginn", "Ende", "Durchgehend geöffnet", "Duplizieren",
        "3. Mai", "24. April", "18. April",
        "Toller Empfang, reichliches Essen, saubere Duschen, Frühstück am Morgen, nichts auszusetzen. Sehr empfehlenswert! Danke an das ganze Team!",
        "Restaurant geöffnet, abwechslungsreiche und günstige Karte. Danke!",
        "Herzlicher Empfang und sehr reichliches Essen, es war perfekt!",
        "Meine Antwort", "Vielen Dank für Ihre Bewertung, Denis! Bis bald!", "Antworten", "Melden",
        "Fotos der Community", "Hinzugefügt von {qui}",
        "Um Ihren Betrieb zu bewerben,", "melden Sie sich auf der Website an.",
    ],
    "es": [
        "¿Conoce",
        "¿Sabía que Michelin Truckfly también existe",
        "para propietarios de establecimientos?",
        "Restaurante", "Aparcamiento", "Gasolinera", "Estación de lavado", "Taller",
        "La comunidad en cifras",
        "2,3 M", "702.000", "135.000",
        "descargas", "países europeos", "idiomas disponibles", "usuarios", "establecimientos registrados",
        "¿Tiene un establecimiento en Michelin Truckfly?",
        "¡Actualice su información!",
        "¿Todavía no está en Michelin Truckfly?",
        "¡Cree su cuenta y añada su establecimiento!",
        "Nombre y datos de contacto", "Servicios ofrecidos", "Fotos", "Horarios",
        "Descubra los comentarios y las fotos de la comunidad",
        "Mi lugar", "Mi cuenta",
        "Mi establecimiento", "Mis servicios y fotos", "Mis horarios de apertura", "Mis comentarios",
        "Nombre del establecimiento", "Dirección", "Código postal", "Ciudad", "Teléfono",
        "Guardar", "✓ Guardado",
        "Mis servicios", "Restaurante de carretera", "Duchas", "Aparcamiento para camiones", "Wifi", "Aseos", "Aparcamiento vigilado",
        "Mi foto", "Arrastre su foto aquí",
        "Lunes", "Martes", "Miércoles", "Inicio", "Fin", "Jornada continua", "Duplicar",
        "3 de mayo", "24 de abril", "18 de abril",
        "Muy buena acogida, comida abundante, duchas limpias, desayuno por la mañana, nada que objetar. ¡Lo recomiendo! ¡Gracias a todo el equipo!",
        "Restaurante abierto, menú variado y barato. ¡Gracias!",
        "Acogida cálida y comida muy abundante, ¡fue perfecto!",
        "Mi respuesta", "¡Muchas gracias por su comentario, Denis! ¡Hasta pronto!", "Responder", "Denunciar",
        "Fotos de la comunidad", "Añadida por {qui}",
        "Para promocionar su establecimiento,", "inicie sesión en el sitio web.",
    ],
    "it": [
        "Conosce",
        "Sapeva che Michelin Truckfly esiste anche",
        "per i titolari di attività?",
        "Ristorante", "Parcheggio", "Stazione di servizio", "Autolavaggio", "Officina",
        "La community in cifre",
        "2,3 Mln", "702.000", "135.000",
        "download", "paesi europei", "lingue disponibili", "utenti", "attività presenti",
        "Ha un'attività su Michelin Truckfly?",
        "Aggiorni le sue informazioni!",
        "Non è ancora su Michelin Truckfly?",
        "Crei il suo account e aggiunga la sua attività!",
        "Nome e recapiti", "Servizi offerti", "Foto", "Orari",
        "Scopra le recensioni e le foto della community",
        "Il mio luogo", "Il mio account",
        "La mia attività", "I miei servizi e foto", "I miei orari di apertura", "Le mie recensioni",
        "Nome dell'attività", "Indirizzo", "CAP", "Città", "Telefono",
        "Salva", "✓ Salvato",
        "I miei servizi", "Ristorante per camionisti", "Docce", "Parcheggio mezzi pesanti", "Wi-Fi", "Servizi igienici", "Parcheggio sorvegliato",
        "La mia foto", "Trascini qui la sua foto",
        "Lunedì", "Martedì", "Mercoledì", "Inizio", "Fine", "Orario continuato", "Duplica",
        "3 maggio", "24 aprile", "18 aprile",
        "Ottima accoglienza, pasti abbondanti, docce pulite, colazione al mattino, niente da ridire. Lo consiglio! Grazie a tutto lo staff!",
        "Ristorante aperto, menù vario ed economico. Grazie!",
        "Accoglienza calorosa e pasti molto abbondanti, è stato perfetto!",
        "La mia risposta", "Grazie mille per la recensione, Denis! A presto!", "Rispondi", "Segnala",
        "Foto della community", "Aggiunta da {qui}",
        "Per promuovere la sua attività,", "acceda al sito web.",
    ],
    "nl": [
        "Kent u",
        "Wist u dat Michelin Truckfly er ook is",
        "voor eigenaren van bedrijven?",
        "Restaurant", "Parkeerplaats", "Tankstation", "Wasstraat", "Garage",
        "De community in cijfers",
        "2,3 mln", "702.000", "135.000",
        "downloads", "Europese landen", "beschikbare talen", "gebruikers", "vermelde bedrijven",
        "Staat uw bedrijf al op Michelin Truckfly?",
        "Werk uw gegevens bij!",
        "Nog niet op Michelin Truckfly?",
        "Maak uw account aan en voeg uw bedrijf toe!",
        "Naam en contactgegevens", "Aangeboden diensten", "Foto's", "Openingstijden",
        "Bekijk de reviews en foto's van de community",
        "Mijn locatie", "Mijn account",
        "Mijn bedrijf", "Mijn diensten en foto's", "Mijn openingstijden", "Mijn reviews",
        "Naam van het bedrijf", "Adres", "Postcode", "Plaats", "Telefoon",
        "Opslaan", "✓ Opgeslagen",
        "Mijn diensten", "Wegrestaurant", "Douches", "Vrachtwagenparkeerplaats", "Wifi", "Toiletten", "Bewaakte parkeerplaats",
        "Mijn foto", "Sleep uw foto hierheen",
        "Maandag", "Dinsdag", "Woensdag", "Begin", "Einde", "Doorlopend open", "Dupliceren",
        "3 mei", "24 april", "18 april",
        "Geweldige ontvangst, royale maaltijden, schone douches, ontbijt in de ochtend, niets op aan te merken. Echt een aanrader! Bedankt aan het hele team!",
        "Restaurant open, gevarieerd en betaalbaar menu. Bedankt!",
        "Hartelijke ontvangst en zeer royale maaltijden, het was perfect!",
        "Mijn antwoord", "Hartelijk dank voor uw review, Denis! Tot snel!", "Beantwoorden", "Melden",
        "Foto's van de community", "Toegevoegd door {qui}",
        "Om uw bedrijf te promoten,", "logt u in op de website.",
    ],
    "pl": [
        "Znasz",
        "Czy wiesz, że Michelin Truckfly jest też",
        "dla właścicieli obiektów?",
        "Restauracja", "Parking", "Stacja paliw", "Myjnia", "Warsztat",
        "Społeczność w liczbach",
        "2,3 mln", "702 000", "135 000",
        "pobrań", "krajów europejskich", "dostępnych języków", "użytkowników", "obiektów w bazie",
        "Masz obiekt w Michelin Truckfly?",
        "Zaktualizuj swoje dane!",
        "Nie ma cię jeszcze w Michelin Truckfly?",
        "Załóż konto i dodaj swój obiekt!",
        "Nazwa i dane kontaktowe", "Oferowane usługi", "Zdjęcia", "Godziny otwarcia",
        "Zobacz opinie i zdjęcia społeczności",
        "Moje miejsce", "Moje konto",
        "Mój obiekt", "Moje usługi i zdjęcia", "Moje godziny otwarcia", "Moje opinie",
        "Nazwa obiektu", "Adres", "Kod pocztowy", "Miasto", "Telefon",
        "Zapisz", "✓ Zapisano",
        "Moje usługi", "Restauracja dla kierowców", "Prysznice", "Parking dla ciężarówek", "Wi-Fi", "Toalety", "Parking strzeżony",
        "Moje zdjęcie", "Przeciągnij tutaj zdjęcie",
        "Poniedziałek", "Wtorek", "Środa", "Od", "Do", "Bez przerwy", "Powiel",
        "3 maja", "24 kwietnia", "18 kwietnia",
        "Świetne przyjęcie, obfite posiłki, czyste prysznice, śniadanie rano, nie ma się do czego przyczepić. Polecam! Dziękuję całemu zespołowi!",
        "Restauracja otwarta, urozmaicone i tanie menu. Dziękuję!",
        "Serdeczne przyjęcie i bardzo obfite posiłki, było idealnie!",
        "Moja odpowiedź", "Bardzo dziękujemy za opinię, Denis! Do zobaczenia!", "Odpowiedz", "Zgłoś",
        "Zdjęcia społeczności", "Dodane przez: {qui}",
        "Aby promować swój obiekt,", "zaloguj się na stronie internetowej.",
    ],
}

for langue, valeurs in T.items():
    assert len(valeurs) == len(CLES), (langue, len(valeurs), len(CLES))
    T[langue] = dict(zip(CLES, valeurs))
